### ISSUE TITLE
Fehler im BidiFlow

### ISSUE THREAD

**Issue by Muenze** [Norwae/ignifera#2]
```
13:51:09.230 [server-akka.actor.default-dispatcher-17] ERROR akka.actor.ActorSystemImpl - Internal server error, sending 500 response
akka.http.impl.util.One2OneBidiFlow$OutputTruncationException: Inner flow was completed without producing result elements for 1 outstanding elements
	at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:21) ~[akka-http-core_2.12-10.0.9.jar:?]
	at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:21) ~[akka-http-core_2.12-10.0.9.jar:?]
	at akka.http.impl.util.One2OneBidiFlow$One2OneBidi$$anon$1$$anon$4.onUpstreamFinish(One2OneBidiFlow.scala:96) ~[akka-http-core_2.12-10.0.9.jar:?]
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:497) ~[akka-stream_2.12-2.5.8.jar:?]
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:371) ~[akka-stream_2.12-2.5.8.jar:?]
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:584) ~[akka-stream_2.12-2.5.8.jar:?]
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:468) ~[akka-stream_2.12-2.5.8.jar:?]
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:559) ~[akka-stream_2.12-2.5.8.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:741) ~[akka-stream_2.12-2.5.8.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:756) ~[akka-stream_2.12-2.5.8.jar:?]
	at akka.actor.Actor.aroundReceive(Actor.scala:517) ~[akka-actor_2.12-2.5.8.jar:?]
	at akka.actor.Actor.aroundReceive$(Actor.scala:515) ~[akka-actor_2.12-2.5.8.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:666) ~[akka-stream_2.12-2.5.8.jar:?]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527) [akka-actor_2.12-2.5.8.jar:?]
	at akka.actor.ActorCell.invoke(ActorCell.scala:496) [akka-actor_2.12-2.5.8.jar:?]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.12-2.5.8.jar:?]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.12-2.5.8.jar:?]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.12-2.5.8.jar:?]
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [akka-actor_2.12-2.5.8.jar:?]
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [akka-actor_2.12-2.5.8.jar:?]
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [akka-actor_2.12-2.5.8.jar:?]
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [akka-actor_2.12-2.5.8.jar:?]
13:51:09.236 [server-akka.actor.default-dispatcher-17] ERROR akka.actor.ActorSystemImpl - Internal server error, sending 500 response
akka.http.impl.util.One2OneBidiFlow$OutputTruncationException: Inner flow was completed without producing result elements for 1 outstanding elements
	at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:21) ~[akka-http-core_2.12-10.0.9.jar:?]
	at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:21) ~[akka-http-core_2.12-10.0.9.jar:?]
	at akka.http.impl.util.One2OneBidiFlow$One2OneBidi$$anon$1$$anon$4.onUpstreamFinish(One2OneBidiFlow.scala:96) ~[akka-http-core_2.12-10.0.9.jar:?]
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:497) ~[akka-stream_2.12-2.5.8.jar:?]
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:371) ~[akka-stream_2.12-2.5.8.jar:?]
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:584) ~[akka-stream_2.12-2.5.8.jar:?]
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:468) ~[akka-stream_2.12-2.5.8.jar:?]
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:559) ~[akka-stream_2.12-2.5.8.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:741) ~[akka-stream_2.12-2.5.8.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:756) ~[akka-stream_2.12-2.5.8.jar:?]
	at akka.actor.Actor.aroundReceive(Actor.scala:517) ~[akka-actor_2.12-2.5.8.jar:?]
	at akka.actor.Actor.aroundReceive$(Actor.scala:515) ~[akka-actor_2.12-2.5.8.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:666) ~[akka-stream_2.12-2.5.8.jar:?]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527) [akka-actor_2.12-2.5.8.jar:?]
	at akka.actor.ActorCell.invoke(ActorCell.scala:496) [akka-actor_2.12-2.5.8.jar:?]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.12-2.5.8.jar:?]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.12-2.5.8.jar:?]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.12-2.5.8.jar:?]
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [akka-actor_2.12-2.5.8.jar:?]
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [akka-actor_2.12-2.5.8.jar:?]
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [akka-actor_2.12-2.5.8.jar:?]
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [akka-actor_2.12-2.5.8.jar:?]
```

Problem trat auf bei vielen Requests in kurzer Zeit, z.B. durch Apache Benchmark oder Autocannon.

Meine Einstellung war 

autocannon -c 2 http://localhost/route...

**Comment by stefan-schulz-fashionid** [comment]
Wird mit #3  behoben
